### ISSUE TITLE
The GAS values is slow to update and is not accurate

### ISSUE THREAD

**Issue by saraceni-andrea** [adafruit/Adafruit_CircuitPython_BME680#12]
https://forums.adafruit.com/viewtopic.php?f=60&t=132231

[mod edit - removed key word highlighting from url]

**Comment by caternuson** [comment]
Probably related to #11

**Comment by saraceni-andrea** [comment]
Also on SPI no improvement ... :-(
https://forums.adafruit.com/viewtopic.php?f=60&t=132231&p=736089&hilit=bme680#p736089

**Comment by ladyada** [comment]
not surprising, the SPI is still reading the same data. you could try to compare what the arduino or espruino is sending for commands and let us know if you see any differences in data?

**Comment by markpatterson27** [comment]
Someone correct me if I'm wrong, but it looks like the gas heating duration isn't being set.

https://github.com/adafruit/Adafruit_CircuitPython_BME680/blob/f1b9e6c7539abdda5810ccdc70625981ddc2c5ec/adafruit_bme680.py#L107-L108

If I understand _write() correctly, the above is just writing [0x73, 0x64, 0x65] into incrementing registers 0x5A to 0x5C and not setting the heating duration. It should be changed to something like:
```
        _BME680_BME680_RES_HEAT_0 = const(0x5A)
        _BME680_BME680_GAS_WAIT_0 = const(0x64)

        self._write(_BME680_BME680_RES_HEAT_0, [0x73])   # approx 320 degrees
        self._write(_BME680_BME680_GAS_WAIT_0, [0x65])   # 148ms
```

**Comment by saraceni-andrea** [comment]
Hi, the latest update of **adafruit_bme680.py** (release **3.1.3**) on CircuitPython 5.0 and Bundle 20200307 works perfectly!

Tested via i2c on:

* Feather M4 Express
* ItsyBitsy M4
* Trinket M0

**THANK YOU VERY MUCH**
