### ISSUE TITLE
SPI broken?

### ISSUE THREAD

**Issue by 0x6470** [adafruit/Adafruit_CircuitPython_BME680#17]
I tried to implement this library in order to read the data form this sensor.
Here's my code:
```
import sys, time
import board
import busio
import digitalio
import adafruit_bme680

cs = digitalio.DigitalInOut(board.D5)
spi = busio.SPI(board.SCLK, board.MOSI, board.MISO)

bme680 = adafruit_bme680.Adafruit_BME680_SPI(spi, cs)
...
```
I get the error `"Failed to find BME680! Chip ID 0xff"`
Changing the value in line 45 of adafruit_bme680.py didn't help me.
I checked my wiring many times and also got myself a second sensor, which didn't work (with SPI) either.
Strangely both of them work, when connected via I2C.

I'm running a Raspberry Pi Zero W (Yes, SPI and I2C are enabled via raspi-config) with openHABian, but I also tried it on a Raspberry Pi 3 B+ with Raspbian, just to get the same error.

**Comment by makermelissa** [comment]
Hi thanks for reporting this. I'm wondering if there's some difference between running it on a native CircuitPython board and on the Raspberry Pi that's causing the error.

**Comment by barbudor** [comment]
@0x6470 , Is it an original Adafruit breakout ?
It may looks like the SDO pin (=MISO) is stuck to VCC (read ID as 0xFF)
Connecting SDO to VCC is required to select the default I2C address of 0x77. Your module may have the SDO pin stuck to VCC.
Could you please check with a ohm meter what resistance you can read between SDO and VCC ?

**Comment by 0x6470** [comment]
Yes, it's an official board, I bought it from an official distributor (Eckstein GmbH).
The resistance is around 10 kOhm, when running via I2C.

**Comment by barbudor** [comment]
@0x6470 I have no problems with a BME280 which driver is exactly build on the same structure.
May be you could join us on Adafruit Discord channel #help-with-raspberry-pi ?
Someone with a BME680 will be able to help there. I'm from Europe too and I'll be available tomorrow

**Comment by makermelissa** [comment]
The BME680 is a bit different than the BME280 in terms of SPI. See https://github.com/adafruit/Adafruit_CircuitPython_BME680/pull/16#issuecomment-472303013 from the last PR. I'll leave this open for when I get a chance to test on a RPi.

**Comment by caternuson** [comment]
@0x6470 Post a photo of your setup showing how you are wiring everything together.

BME680 on RPi via SPI checks out OK.

- 3.3V to VIN
- GND to GND
- SCLK to SCK
- MISO to SDO
- MOSI to SDI
- BCM5 to CS

![rpi_bme680](https://user-images.githubusercontent.com/8755041/59209228-a3eec900-8b5f-11e9-8cf5-a90514b1c4e0.jpg)

```python
pi@raspberrypi:~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board, busio, digitalio
>>> import adafruit_bme680
>>> cs = digitalio.DigitalInOut(board.D5)
>>> spi = busio.SPI(board.SCLK, board.MOSI, board.MISO)
>>> bme680 = adafruit_bme680.Adafruit_BME680_SPI(spi, cs)
>>> bme680.temperature
23.73234375
>>> bme680.humidity
44.72550176005509
>>> bme680.pressure
1015.1474238206924
>>>
```

**Comment by makermelissa** [comment]
Thanks for testing this @caternuson

**Comment by 0x6470** [comment]
I'm so sorry...
I firstly connected the sensor via female-female jumper wires,
then switched over to female-male ones to showcase my connections.
It turned out that one of the f-f wires (chip select) had a loose connection.
Sometimes it can be that easy...
Thanks anyway for taking your time.
