### ISSUE TITLE
Support for BME680 IAQ readings

### ISSUE THREAD

**Issue by ruralcoder** [adafruit/Adafruit_CircuitPython_BME680#21]
The BME680's  BSEC provides an indoor air quality (IAQ) output which is not exposed in your library.

**Comment by ladyada** [comment]
hiya - it is not possible - the code is under NDA!

**Comment by ruralcoder** [comment]
Are you telling me that bosch that their business is to sell sensors and other's to use, blocked the IAQ portion?

**Comment by ladyada** [comment]
yes
