### ISSUE TITLE
Please explain filter_size in documentation

### ISSUE THREAD

**Issue by Napsty** [adafruit/Adafruit_CircuitPython_BME680#28]
The current documentation (https://circuitpython.readthedocs.io/projects/bme680/en/latest/api.html) describes `filter_size` as:

> filter_size
    The filter size for the built in IIR filter

Sorry but I don't understand what this means. Does it refer to the sensors current status (e.g. calibrating)?

https://www.home-assistant.io/integrations/bme680 documents it as:

> filter_size
    (integer)(Optional)
    IIR filter size as described in the sensor datasheet. Can be 0 (off), 1, 3, 7, 15, 31, 63 or 127.
    Default value: 3

But a bit more information (what does it do?) would be really helpful.

**Comment by FoamyGuy** [comment]
The Datasheet located here: [https://cdn-shop.adafruit.com/product-files/3660/BME680.pdf](https://cdn-shop.adafruit.com/product-files/3660/BME680.pdf) has some more details. 

In particular check out sections 3.3.4 on page 18 and section 5.3.2.4 on page 28. The describe the IR Filter value and how it's used as well as the possible values for it.
