### ISSUE TITLE
Newest example needs licensed

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_BME680#39]
It seems the wires got crossed a bit between #38 and #36. The former added a new example, and the latter moved to pre-commit and added license information to everything. 

Since these occured at roughly the same time the newest example from #38 did not get included when the actions ran on #36 so it did pass at the time it ran, but the repo currently failing due to missing license on this new example.

@caternuson if you are around and can PR the the copyright / license lines into that example go ahead and do that. If not, no worries I can circle back later tonight and make one to add these.

**Comment by caternuson** [comment]
Thanks for spotting this. I think simple edit in #40 is all that's needed?

**Comment by FoamyGuy** [comment]
resolved by #40
