### ISSUE TITLE
Gas resistance calculation showing incorrect results for BME688

### ISSUE THREAD

**Issue by Technodad** [adafruit/Adafruit_CircuitPython_BME680#42]
While the BME680 library is recommended for the BME688, it appears the calculations for gas resistance are different for the two sensors per @adafruit_support_carter in this [support forum thread](https://forums.adafruit.com/viewtopic.php?f=60&t=180923&p=881036#p881036) post on July 13.

Suggest either splitting the 688 into its own library, or adding logic to the combined library to detect the chip type and use the appropriate calculation. The former will save a bit on library size, but would require the BME688 project pages to be updated.

**Comment by ladyada** [comment]
yeah there's no way to detect between the chips that we found so we'll have to just make a subclass or yeah maybe a new library

@caternuson wanna avoid pn532 and look at this instead

**Comment by caternuson** [comment]
@ladyada yep. bme688 in hand and taking a look.

**Comment by caternuson** [comment]
Should be fixed with #43 and release in 3.4.0:
https://github.com/adafruit/Adafruit_CircuitPython_BME680/releases/tag/3.4.0
