### ISSUE TITLE
Error during __init__ - Failed to find BME680! Chip ID 0x0

### ISSUE THREAD

**Issue by joshooaj** [adafruit/Adafruit_CircuitPython_BME680#44]
I just plugged in the BME688, copied over this lib and the adafruit_bus_device lib, and tested out the sample code but I get the following error. I checked the datasheet for the BME688 to confirm the chip ID is still stored at the 0xD0 register for I2C. 

```text
>>> bme680 = adafruit_bme680.Adafruit_BME680_I2C(i2c, debug=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_bme680.py", line 436, in __init__
  File "adafruit_bme680.py", line 136, in __init__
RuntimeError: Failed to find BME680! Chip ID 0x0
>>> import board
>>> import adafruit_bme680
>>> i2c = board.I2C()
>>> sensor = adafruit_bme680.Adafruit_BME680_I2C(i2c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_bme680.py", line 436, in __init__
  File "adafruit_bme680.py", line 136, in __init__
RuntimeError: Failed to find BME680! Chip ID 0x0
>>>

```

**Comment by Technodad** [comment]
Check to make sure you don’t have another I2C device at the address of your BME688. This tripped me up for a while on a FunHouse board, which has two onboard sensors on the I2C bus.

**Comment by joshooaj** [comment]
Hah, thanks! I'm using the FunHouse board as it was the closest thing to me with stemma QT connectors 😂

**Comment by ladyada** [comment]
for this kind of tech support please post in the adafruit forums or on discord. thanks! :)
