### ISSUE TITLE
Slow refresh rate

### ISSUE THREAD

**Issue by joezilla86** [adafruit/Adafruit_CircuitPython_BME680#65]
Between 3.4.13 and 3.5 release, the rate at which the sensor returns readings has drastically slowed. I can get a new reading every ~0.3 seconds (the sensor can return readings much faster than this, but they only update about every 0.3 seconds). Whereas when I change to 3.5.0 the readings only update about every 4 seconds.

I tried the following minimal code using a QtPY ESP32-S2 and a BME688 and the only thing I'm changing is the version of the BME680 library loaded on the board.

```
import board
import busio
import time
from adafruit_bme680 import Adafruit_BME680_I2C as BME688

i2c = busio.I2C(board.SCL1, board.SDA1)
sensor = BME688(i2c)

while True:
    print('Temp: {} C \tPres: {} hPa\t{}'.format(sensor.temperature, sensor.pressure, time.monotonic()))
    #time.sleep(.25)
```

**Comment by CTho9305** [comment]
Could you check whether this is fixed in the latest version?

**Comment by FoamyGuy** [comment]
Closing this for now. I believe #67 should resolve it. If you get back to this and try the newest version and still have the problem feel free to re-open.
